export const SEE_LINKS={
    "cocktail_box": "seecocktailbox",
    "aux_battery": "seeauxbattery",
    "motor_controller": "seemotorcontroller",
    "on_board_charger": "seeonboardcharger",
    "dc_dc": "seedcdc",
    "stark": "seestark",
    "arc_reactor_assembly": "seearcreactorassembly",
    "cell": "seecell",
    "bms": "seebms",
    "battery": "seebattery",
    "battery_box": "seebatterybox",
    "signal_connector": "seesignalconnector",
    "tmc": "seetmc",
    "reservoir": "seereservoir",
    "brake_switch": "seebrakeswitch",
    "front_tyre": "seefronttyre",
    "rear_tyre": "seereartyre",
    "front_rim": "seefrontrim",
    "rear_rim": "seerearrim",
    "rotor": "seerotor",
    "caliper": "seecaliper",
    "upper_and_lower_cone": "seeupperandlowercone",
    "fork_2_bearing": "seefork2bearing",
    "bottom_link": "seebottomlink",
    "fork_and_suspension_assembly_spring": "seeforkandsuspensionassemblyspring",
    "fork_and_suspension_assembly_strut": "seeforkandsuspensionassemblystrut",
    "rear_axle": "seerearaxle",
    "crown_nut": "seecrownnut",
    "mounting_rubber": "seemountingrubber",
    "trailing_arm": "seetrailingarm",
    "drum": "seedrum",
    "brake_plate": "seebrakeplate",
    "hub_assembly": "seehubassembly",
    "gearbox": "seegearbox",
    "motor": "seemotor",
    "muff_cup": "seemuffcup",
    "vehicle_harness": "seevehicleharness",
    "biw": "seebiw",
    "mark": "seemark",
    "telematics": "seetelematics",
    "load_body": "seeloadbody"

};


export const UPDATE_LINKS={
    "cocktail_box":"updatecocktailbox",
    "aux_battery":"updateauxbattery",
    "motor_controller":"updatemotorcontroller",
    "on_board_charger":"updateonboardcharger",
    "dc_dc":"updatedcdc",
    "stark":"updatestark",
    "arc_reactor_assembly":"updatearcreactorassembly",
    "cell":"updatecell",
    "bms":"updatebms",
    "battery":"updatebattery",
    "battery_box":"updatebatterybox",
    "signal_connector":"updatesignalconnector",
    "tmc":"updatetmc",
    "reservoir":"updatereservoir",
    "brake_switch":"updatebrakeswitch",
    "front_tyre":"updatefronttyre",
    "rear_tyre":"updatereartyre",
    "front_rim":"updatefrontrim",
    "rear_rim":"updaterearrim",
    "rotor":"updaterotor",
    "caliper":"updatecaliper",
    "upper_and_lower_cone":"updateupperandlowercone",
    "fork_2_bearing":"updatefork2bearing",
    "bottom_link":"updatebottomlink",
    "fork_and_suspension_assembly_spring":"updateforkandsuspensionassemblyspring",
    "fork_and_suspension_assembly_strut":"updateforkandsuspensionassemblystrut",
    "rear_axle":"updaterearaxle",
    "crown_nut":"updatecrownnut",
    "mounting_rubber":"updatemountingrubber",
    "trailing_arm":"updatetrailingarm",
    "drum":"updatedrum",
    "brake_plate":"updatebrakeplate",
    "hub_assembly":"updatehubassembly",
    "gearbox":"updategearbox",
    "motor":"updatemotor",
    "muff_cup":"updatemuffcup",
    "vehicle_harness":"updatevehicleharness",
    "biw":"updatebiw",
    "mark":"updatemark",
    "telematics":"updatetelematics",
    "load_body":"updateloadbody"
 };

 export const ADD_LINKS={
    "cocktail_box":"addcocktailbox",
    "aux_battery":"addauxbattery",
    "motor_controller":"addmotorcontroller",
    "on_board_charger":"addonboardcharger",
    "dc_dc":"adddcdc",
    "stark":"addstark",
    "arc_reactor_assembly":"addarcreactorassembly",
    "cell":"addcell",
    "bms":"addbms",
    "battery":"addbattery",
    "battery_box":"addbatterybox",
    "signal_connector":"addsignalconnector",
    "tmc":"addtmc",
    "reservoir":"addreservoir",
    "brake_switch":"addbrakeswitch",
    "front_tyre":"addfronttyre",
    "rear_tyre":"addreartyre",
    "front_rim":"addfrontrim",
    "rear_rim":"addrearrim",
    "rotor":"addrotor",
    "caliper":"addcaliper",
    "upper_and_lower_cone":"addupperandlowercone",
    "fork_2_bearing":"addfork2bearing",
    "bottom_link":"addbottomlink",
    "fork_and_suspension_assembly_spring":"addforkandsuspensionassemblyspring",
    "fork_and_suspension_assembly_strut":"addforkandsuspensionassemblystrut",
    "rear_axle":"addrearaxle",
    "crown_nut":"addcrownnut",
    "mounting_rubber":"addmountingrubber",
    "trailing_arm":"addtrailingarm",
    "drum":"adddrum",
    "brake_plate":"addbrakeplate",
    "hub_assembly":"addhubassembly",
    "gearbox":"addgearbox",
    "motor":"addmotor",
    "muff_cup":"addmuffcup",
    "vehicle_harness":"addvehicleharness",
    "biw":"addbiw",
    "mark":"addmark",
    "telematics":"addtelematics",
    "load_body":"addloadbody"
 };